### ISSUE TITLE
Drones not attacking Frigs

### ISSUE THREAD

**Issue by Smellyarmpits** [ISeeDEDPpl/Questor#353]
Using the most recent build, questor seems to be using drones to attack battleships and crusiers and guns (weapons) on frigs.  This behavior is intermittent.  Sometimes questor will use both drones and guns on frigs that are scraming/webing but then later in the same pocket drones will work on crusiers/battleships while guns are on a frig.  I have also noticed that questor will sometimes continue doing this even when scrammed/webbed.  

Since there are gun fits are using heavy long range guns it would be helpful if one could set drones to attack all frigs that have the ship aggo'ed, Then assist primary (gun) target.

It would also be helpful if there was a way to graduate gun targets - say guns kill BS-Frig or Frig-BS.

**Comment by Smellyarmpits** [comment]
kk I was using an old character.xml.

**Comment by ISeeDEDPpl** [comment]
if this is still an issue I need a snippit of the console logs.

**Comment by Smellyarmpits** [comment]
Yes it is still doing it.  I have an old .xml file that i added the new gunnery settings to:

 
  <shootWarpScramblersWithPrimaryWeapons>False</shootWarpScramblersWithPrimaryWeapons>
  
  
  <speedNPCFrigatesShouldBeIgnoredByPrimaryWeapons>300</speedNPCFrigatesShouldBeIgnoredByPrimaryWeapons>
  <distanceNPCFrigatesShouldBeIgnoredByPrimaryWeapons>11000</distanceNPCFrigatesShouldBeIgnoredByPrimaryWeapons>

And it is still using drones for BS and guns on frigs.  It really gets me since my cap/ammo is always eaten up with the heavy guns shooting a frig within >11000kms.  Drones should always go for frigs (exist/spawn) and then primary target regardless of what they are currently assigned.  Long guns should always shoot frigs at <20-25kms and if none exist/spawn should  then first cruiser <20-15kms to longest distance and then target nearest battleship.

I am working on getting the new .xml file merged with the old .xml content.  If it still persists, I will post the log.  I am also experience something weird with the console interface.  Sometimes it displays properly and others it gives me:  
![console1](https://f.cloud.github.com/assets/890999/294855/215a5e9a-941d-11e2-86e8-9135a0ce6c69.jpg)

**Comment by Smellyarmpits** [comment]
Here is the log output I think you need:

19:32:59 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [12]
19:32:59 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [12]
19:33:00 [Defense] Shields: [100%] Cap: [59%] Shield Booster: [1] deactivated [1] sec reactivation delay
19:33:01 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [10]
19:33:01 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [10]
19:33:03 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [8]
19:33:03 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [8]
19:33:05 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [6]
19:33:05 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [6]
19:33:07 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [4]
19:33:07 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [4]
19:33:09 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [2]
19:33:09 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [2]
19:33:11 [Combat] Targeting priority target [Guardian Veteran][ID: [truncatedID]51474][1k away] highValueTargets.Count [5]
19:33:13 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [18]
19:33:13 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [18]
19:33:15 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [16]
19:33:15 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [16]
19:33:15 [Salvage] Cargo Container [Guardian Veteran Wreck][1k][ID: [truncatedID]14793] within loot range, unlocking container.
19:33:16 [Combat] Initiating Orbit [Core Admiral][at 10/][ID: [truncatedID]51465]
19:33:17 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [14]
19:33:17 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [14]
19:33:17 [Salvage] Activating tractorbeam [1] on [Corelatis Platoon Leader Wreck][3k][ID: [truncatedID]68181]
19:33:18 [Combat] Activating weapon [2] on [Core Admiral][ID: [truncatedID]51465][53k away]
19:33:19 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [12]
19:33:19 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [12]
19:33:20 [Combat] Activating weapon [1] on [Core Admiral][ID: [truncatedID]51465][53k away]
19:33:20 [Combat] Activating weapon [3] on [Core Admiral][ID: [truncatedID]51465][53k away]
19:33:21 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [10]
19:33:21 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [10]
19:33:22 [Combat] Activating weapon [4] on [Core Admiral][ID: [truncatedID]51465][53k away]
19:33:23 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [8]
19:33:23 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [8]
19:33:24 [Salvage] Cargo Container [Corelatis Platoon Leader Wreck][1k][ID: [truncatedID]68181] within loot range, unlocking container.
19:33:25 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [6]
19:33:25 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [6]
19:33:27 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [4]
19:33:27 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [4]
19:33:29 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [1]
19:33:29 [EntityCache] LockTarget is ignored for [Guardian Veteran][9000885993001251474], can retarget in [1]
19:33:31 [Combat] Targeting priority target [Guardian Veteran][ID: [truncatedID]51474][1k away] highValueTargets.Count [4]
19:33:42 [Defense] Shields: [68%] Cap: [62%] Shield Booster: [1] activated
19:34:00 [Drones] Engaging [ 5 ] drones on [Core Admiral][ID: [truncatedID]51462]52k away]
19:34:01 [Combat] Initiating Orbit [Guardian Veteran][at 10/][ID: [truncatedID]51474]
19:34:03 [Defense] Shields: [99%] Cap: [56%] Shield Booster: [1] deactivated [2] sec reactivation delay
19:34:03 [Combat] Changing [1] with [Multifrequency L][42][TypeID: 262] so we can hit [Guardian Veteran][1k]
19:34:05 [Combat] Activating weapon [1] on [Guardian Veteran][ID: [truncatedID]51474][1k away]
19:34:05 [Combat] Changing [3] with [Multifrequency L][42][TypeID: 262] so we can hit [Guardian Veteran][1k]
19:34:05 [Combat] Changing [4] with [Multifrequency L][42][TypeID: 262] so we can hit [Guardian Veteran][1k]
19:34:07 [Combat] Changing [2] with [Multifrequency L][42][TypeID: 262] so we can hit [Guardian Veteran][1k]
19:34:07 [Combat] Activating weapon [3] on [Guardian Veteran][ID: [truncatedID]51474][1k away]
19:34:07 [Combat] Activating weapon [4] on [Guardian Veteran][ID: [truncatedID]51474][1k away]
19:34:09 [Combat] Activating weapon [2] on [Guardian Veteran][ID: [truncatedID]51474][1k away]

Please let me know if you need more I have it open and ready to post more if you need it.  Thanks in advance btw

**Comment by ISeeDEDPpl** [comment]
What is your
`<!-- Maximum number of targets per value -->`
`<maximumHighValueTargets>4</maximumHighValueTargets><!-- default is 4 -->`
`<maximumLowValueTargets>3</maximumLowValueTargets><!-- default is 3 -->`

and

`<!-- maximum number of wreck targets, at least 1 is required for salvager or tractor beam to work -->`
`<maximumWreckTargets>2</maximumWreckTargets>`
set to?

How many targets can your ship (with skills) manage?
The total of all 3 should be less than the total number or targets your ship can actually target.

**Comment by Smellyarmpits** [comment]
Max targets x7

  <maximumHighValueTargets>2</maximumHighValueTargets>
  <maximumLowValueTargets>5</maximumLowValueTargets>

<maximumWreckTargets>2</maximumWreckTargets>

kk so I will reduce the numbers and test :-)

**Comment by Smellyarmpits** [comment]
lowered the 3 values so they are LESS than the max and the behavior persists

**Comment by Smellyarmpits** [comment]
it also now seems to be ignoring webbers/scramers with guns AND drones with shootwarpscramblerwithprimaryweapons set to false.  Drones should be immediately routed to scramers/webbers should they not?

**Comment by Pluckyduck** [comment]
are you speed tanking? or not?

**Comment by Smellyarmpits** [comment]
yes i can e-mail you my current config

**Comment by ISeeDEDPpl** [comment]
more of the log would be useful, everything from entering the pocket until you see the problem would help.

**Comment by Smellyarmpits** [comment]
I did not let it complete the room here, but questor attacked a turret with drones which is nice since I have the option for turrets selected, but primary guns were assigned to a frig and once finished with the turret the drones when for a cruiser instead of the handful of firgs in the room.  The primary weapons had not finished the frig (6k range) when questor assigned the drones to a crusier.

12:49:07 [CombatMissionCtrl.WaitUntilTargeted [timeout: 15]] Nothing targeted us within [ 15sec]!
12:49:07 [CombatMissionCtrl] Finished Action.WaitUntilTargeted [timeout: 15]
12:49:07 [CombatMissionCtrl] Starting Action.ClearPocket
12:49:08 [Panic] Adding [Centatis Phantasm][ID: [truncatedID]24012] as a PrimaryWeaponPriorityTarget
12:49:09 [Combat] Targeting priority target [Centatis Phantasm][ID: [truncatedID]24012][19k away] highValueTargets.Count [0]
12:49:11 [Combat] Targeting high value target [Centus Slave Lord][ID: [truncatedID]24008][25k away] highValueTargets.Count [1]
12:49:15 [Combat] Targeting high value target [Centum Controller][ID: [truncatedID]24017][20k away] highValueTargets.Count [2]
12:49:17 [Combat] Targeting high value target [Centatis Phantasm][ID: [truncatedID]24011][23k away] highValueTargets.Count [3]
12:49:17 [Drones] [5] Drones Launched
12:49:19 [Combat] Targeting high value target [Centatis Specter][ID: [truncatedID]24013][21k away] highValueTargets.Count [4]
12:49:19 [Drones] Engaging [ 5 ] drones on [Centatis Phantasm][ID: [truncatedID]24012]18k away]
12:49:20 [Combat] Activating weapon [1] on [Centatis Phantasm][ID: [truncatedID]24012][18k away]
12:49:20 [Combat] Activating weapon [2] on [Centatis Phantasm][ID: [truncatedID]24012][18k away]
12:49:22 [Combat] Activating weapon [3] on [Centatis Phantasm][ID: [truncatedID]24012][18k away]
12:49:22 [Combat] Activating weapon [4] on [Centatis Phantasm][ID: [truncatedID]24012][18k away]
12:49:29 [Combat] Targeting priority target [Centatis Phantasm][ID: [truncatedID]24012][17k away] highValueTargets.Count [4]
12:49:29 [Drones] [Centatis Specter][ID: [truncatedID]24013][21k away] is now the target for drones
12:49:30 [Combat] Activating weapon [1] on [Centatis Specter][ID: [truncatedID]24013][21k away]
12:49:30 [Drones] Engaging [ 5 ] drones on [Centatis Specter][ID: [truncatedID]24013]21k away]
12:49:30 [Salvage] Locking [Centatis Phantasm Wreck][17k][ID: [truncatedID]27688][17k away]
12:49:30 [Panic] Adding [Centum Controller][ID: [truncatedID]24017] as a PrimaryWeaponPriorityTarget
12:49:31 [Combat] Targeting high value target [Centus Lord][ID: [truncatedID]24005][26k away] highValueTargets.Count [4]
12:49:35 [Combat] Activating weapon [2] on [Centum Controller][ID: [truncatedID]24017][18k away]
12:49:35 [Combat] Activating weapon [3] on [Centum Controller][ID: [truncatedID]24017][18k away]
12:49:36 [Salvage] Activating tractorbeam [1] on [Centatis Phantasm Wreck][17k][ID: [truncatedID]27688]
12:49:37 [Combat] Activating weapon [4] on [Centum Controller][ID: [truncatedID]24017][18k away]
12:49:39 [Combat] Activating weapon [1] on [Centum Controller][ID: [truncatedID]24017][18k away]
12:49:58 [Combat] Targeting priority target [Centum Controller][ID: [truncatedID]24017][16k away] highValueTargets.Count [4]
12:49:59 [Panic] Adding [Centatis Phantasm][ID: [truncatedID]24011] as a PrimaryWeaponPriorityTarget
12:50:01 [Combat] Activating weapon [1] on [Centatis Phantasm][ID: [truncatedID]24011][22k away]
12:50:03 [Combat] Activating weapon [4] on [Centatis Phantasm][ID: [truncatedID]24011][22k away]
12:50:04 [Salvage] Cargo Container [Centatis Phantasm Wreck][2k][ID: [truncatedID]27688] within loot range, unlocking container.
12:50:05 [Combat] Activating weapon [2] on [Centatis Phantasm][ID: [truncatedID]24011][22k away]
12:50:05 [Combat] Activating weapon [3] on [Centatis Phantasm][ID: [truncatedID]24011][22k away]
12:50:05 [Salvage] Opening container [Centatis Phantasm Wreck][1k][ID: [truncatedID]27688]
12:50:07 [Panic] Adding [Centatis Specter][ID: [truncatedID]24013] as a PrimaryWeaponPriorityTarget
12:50:10 [Salvage] Locking [Centatis Phantasm Wreck][22k][ID: [truncatedID]28904][22k away]
12:50:11 [Combat] Activating weapon [1] on [Centatis Specter][ID: [truncatedID]24013][23k away]
12:50:11 [Salvage] Opening container [Centatis Phantasm Wreck][1k][ID: [truncatedID]27688]
12:50:11 [Salvage.LootWrecks] Container [Centatis Phantasm Wreck][1k][ID: [truncatedID]27688] contained no valuable items
12:50:15 [Combat] Activating weapon [2] on [Centatis Specter][ID: [truncatedID]24013][23k away]
12:50:15 [Combat] Activating weapon [3] on [Centatis Specter][ID: [truncatedID]24013][23k away]
12:50:16 [Combat] Targeting priority target [Centatis Specter][ID: [truncatedID]24013][23k away] highValueTargets.Count [2]
12:50:16 [Drones] [Centus Lord][ID: [truncatedID]24005][24k away] is now the target for drones
12:50:17 [Drones] Engaging [ 5 ] drones on [Centus Lord][ID: [truncatedID]24005]24k away]
12:50:17 [Panic] Adding [Centus Lord][ID: [truncatedID]24005] as a PrimaryWeaponPriorityTarget
12:50:18 [Salvage] Activating tractorbeam [1] on [Centatis Phantasm Wreck][22k][ID: [truncatedID]28904]
12:50:21 [Combat] Activating weapon [1] on [Centus Lord][ID: [truncatedID]24005][24k away]
12:50:23 [Combat] Activating weapon [4] on [Centus Lord][ID: [truncatedID]24005][24k away]
12:50:25 [Combat] Activating weapon [2] on [Centus Lord][ID: [truncatedID]24005][24k away]
12:50:25 [Combat] Activating weapon [3] on [Centus Lord][ID: [truncatedID]24005][24k away]
12:50:40 [Combat] Targeting priority target [Centus Lord][ID: [truncatedID]24005][23k away] highValueTargets.Count [1]
12:50:40 [Drones] Engaging [ 5 ] drones on [Centus Slave Lord][ID: [truncatedID]24008]37k away]
12:50:42 [Defense] Shields: [65%] Cap: [79%] Shield Booster: [1] activated
12:50:42 [Panic] Adding [Centus Slave Lord][ID: [truncatedID]24008] as a PrimaryWeaponPriorityTarget
12:50:45 [Combat] Activating weapon [1] on [Centus Slave Lord][ID: [truncatedID]24008][37k away]
12:50:45 [Combat] Activating weapon [3] on [Centus Slave Lord][ID: [truncatedID]24008][37k away]
12:50:47 [Combat] Activating weapon [2] on [Centus Slave Lord][ID: [truncatedID]24008][38k away]
12:50:47 [Combat] Activating weapon [4] on [Centus Slave Lord][ID: [truncatedID]24008][38k away]
12:50:56 [Salvage] Cargo Container [Centatis Phantasm Wreck][1k][ID: [truncatedID]28904] within loot range, unlocking container.
12:50:57 [Salvage] Opening container [Centatis Phantasm Wreck][1k][ID: [truncatedID]28904]
12:51:01 [Defense] Shields: [98%] Cap: [71%] Shield Booster: [1] deactivated [1] sec reactivation delay
12:51:01 [Salvage] Locking [Centatis Specter Wreck][23k][ID: [truncatedID]29152][23k away]
12:51:02 [Salvage] Opening container [Centatis Phantasm Wreck][1k][ID: [truncatedID]28904]
12:51:02 [Salvage.LootWrecks] Container [Centatis Phantasm Wreck][1k][ID: [truncatedID]28904] contained no valuable items
12:51:06 [Salvage] Activating tractorbeam [1] on [Centatis Specter Wreck][23k][ID: [truncatedID]29152]
12:51:07 [Drones] Recalling [ 5 ] drones because no NPC is targeting us within dronerange
12:51:14 [CombatMissionCtrl] Finished Action.ClearPocket
12:51:14 [CombatMissionCtrl] Starting Action.Activate [target: Acceleration Gate]
12:51:27 [CombatMissionCtrl] Activate: We are too close to [Acceleration Gate] Initiating orbit
12:51:39 [CombatMissionCtrl] Bookmarking pocket for salvaging [Junk: 1751]
12:51:39 [CombatMissionCtrl] Activate: [Acceleration Gate] Move to next pocket after reload command and change state to 'NextPocket'
12:52:15 [CombatMissionCtrl] We have moved to the next Pocket [10076k away]
12:52:15 [Statistics: WritePocketStatistics] Writing pocket statistics to [ C:\InnerPrime.NET Programs\log_MyEVECharacterNameRedacted_\pocketstats_MyEVECharacterNameRedacted_ - Downing The Slavers (2 of 2) - 1 - PocketStatistics.csv ] and clearing stats for next pocket
12:52:16 [Cache.SetmissionXmlPath] [C:\InnerPrime.NET Programs\Minmatar L4 Missions\Downing The Slavers (2 of 2)-Sansha's Nation.xml] not found.
12:52:16 [Cache.SetmissionXmlPath] [C:\InnerPrime.NET Programs\Minmatar L4 Missions\Downing The Slavers (2 of 2).xml] not found
12:52:16 [CombatMissionCtrl] No mission actions specified, loading default actions
12:52:16 [-] -----------------------------------------------------------------
12:52:16 [-] -----------------------------------------------------------------
12:52:16 [CombatMissionCtrl] Mission Timer Currently At: [9] min
12:52:16 [CombatMissionCtrl] Max Range is currently: 100k
12:52:16 [-] -----------------------------------------------------------------
12:52:16 [-] -----------------------------------------------------------------
12:52:16 [CombatMissionCtrl] Pocket [1] loaded, executing the following actions
12:52:16 [CombatMissionCtrl] Action [ 1 ] WaitUntilTargeted [timeout: 15]
12:52:16 [CombatMissionCtrl] Action [ 2 ] ClearPocket
12:52:16 [CombatMissionCtrl] Action [ 3 ] Done
12:52:16 [-] -----------------------------------------------------------------
12:52:16 [-] -----------------------------------------------------------------
12:52:16 [Statistics.ObjectStatistics] Logging info on the [40] objects in this pocket to [C:\InnerPrime.NET Programs\log_MyEVECharacterNameRedacted_\PocketObjectStats_MyEVECharacterNameRedacted_ - Downing The Slavers (2 of 2) - 1 - ObjectStatistics.csv]
12:52:27 [Combat] Targeting high value target [Sansha Cruise Missile Battery][ID: [truncatedID]24086][23k away] highValueTargets.Count [1]
12:52:27 [CombatMissionCtrl.WaitUntilTargeted [timeout: 15]] We have been targeted!
12:52:27 [CombatMissionCtrl] Finished Action.WaitUntilTargeted [timeout: 15]
12:52:27 [CombatMissionCtrl] Starting Action.ClearPocket
12:52:28 [Panic] Adding [Centatis Specter][ID: [truncatedID]24091] as a PrimaryWeaponPriorityTarget
12:52:29 [Combat] Targeting priority target [Centatis Specter][ID: [truncatedID]24091][22k away] highValueTargets.Count [2]
12:52:31 [Combat] Targeting high value target [Sansha Cruise Missile Battery][ID: [truncatedID]24068][23k away] highValueTargets.Count [3]
12:52:33 [Combat] Targeting high value target [Sansha Stasis Tower][ID: [truncatedID]24060][24k away] highValueTargets.Count [4]
12:52:34 [Drones] [5] Drones Launched
12:52:41 [Drones] [Centatis Specter][ID: [truncatedID]24091][22k away] is now the target for drones
12:52:42 [Combat] Activating weapon [1] on [Centatis Specter][ID: [truncatedID]24091][22k away]
12:52:42 [Combat] Activating weapon [2] on [Centatis Specter][ID: [truncatedID]24091][22k away]
12:52:42 [Drones] Engaging [ 5 ] drones on [Centatis Specter][ID: [truncatedID]24091]22k away]
12:52:44 [Combat] Activating weapon [3] on [Centatis Specter][ID: [truncatedID]24091][22k away]
12:52:44 [Combat] Activating weapon [4] on [Centatis Specter][ID: [truncatedID]24091][22k away]
12:52:46 [Drones] Engaging [ 5 ] drones on [Sansha Cruise Missile Battery][ID: [truncatedID]24086]23k away]
12:52:47 [Combat] Targeting high value target [Centatis Specter][ID: [truncatedID]24094][23k away] highValueTargets.Count [4]
12:52:47 [Panic] Adding [Sansha's Demon][ID: [truncatedID]24090] as a PrimaryWeaponPriorityTarget
12:52:47 [CombatMissionCtrl.ClearPocket] Initiating Orbit [Sansha's Demon][at 40k][ID: [truncatedID]24090]
12:52:50 [Combat] Activating weapon [1] on [Sansha Cruise Missile Battery][ID: [truncatedID]24086][23k away]
12:52:50 [Combat] Activating weapon [2] on [Sansha Cruise Missile Battery][ID: [truncatedID]24086][23k away]
12:52:55 [Combat] Activating weapon [3] on [Sansha Cruise Missile Battery][ID: [truncatedID]24086][23k away]
12:52:55 [Combat] Activating weapon [4] on [Sansha Cruise Missile Battery][ID: [truncatedID]24086][23k away]
12:52:58 [Cache.GetBesttarget] [Sansha's Demon] was removed from the PrimaryWeaponsPriorityTarget list because it was inside [9748] meters and going [898] meters per second
12:53:00 [Combat] Targeting high value target [Centatis Specter][ID: [truncatedID]24093][24k away] highValueTargets.Count [4]
12:53:00 [Drones] [Centatis Specter][ID: [truncatedID]24094][22k away] is now the target for drones
12:53:01 [Combat] Activating weapon [1] on [Centatis Specter][ID: [truncatedID]24094][22k away]
12:53:01 [Drones] Engaging [ 5 ] drones on [Centatis Specter][ID: [truncatedID]24094]22k away]
12:53:03 [Combat] Activating weapon [3] on [Centatis Specter][ID: [truncatedID]24094][22k away]
12:53:03 [Combat] Activating weapon [4] on [Centatis Specter][ID: [truncatedID]24094][22k away]
12:53:07 [Combat] Activating weapon [2] on [Centatis Specter][ID: [truncatedID]24094][22k away]
12:53:11 [Defense] Shields: [62%] Cap: [77%] Shield Booster: [1] activated
12:53:11 [Drones] [Centatis Specter][ID: [truncatedID]24093][24k away] is now the target for drones
12:53:12 [Combat] Targeting high value target [Centus Savage Lord][ID: [truncatedID]24098][29k away] highValueTargets.Count [4]
12:53:12 [Drones] Engaging [ 5 ] drones on [Centatis Specter][ID: [truncatedID]24093]24k away]
12:53:14 [Salvage] Locking [Centatis Specter Wreck][23k][ID: [truncatedID]34564][23k away]
12:53:15 [Combat] Activating weapon [2] on [Centatis Specter][ID: [truncatedID]24093][24k away]
12:53:17 [Combat] Activating weapon [1] on [Centatis Specter][ID: [truncatedID]24093][24k away]
12:53:17 [Combat] Activating weapon [4] on [Centatis Specter][ID: [truncatedID]24093][24k away]
12:53:18 [Combat] Targeting high value target [Sansha Slaver][ID: [truncatedID]24071][21k away] highValueTargets.Count [4]
12:53:18 [Drones] [Sansha Cruise Missile Battery][ID: [truncatedID]24068][24k away] is now the target for drones
12:53:19 [Drones] Engaging [ 5 ] drones on [Sansha Cruise Missile Battery][ID: [truncatedID]24068]24k away]
12:53:19 [Salvage] Activating tractorbeam [1] on [Centatis Specter Wreck][23k][ID: [truncatedID]34564]
12:53:23 [Combat] Activating weapon [2] on [Centus Savage Lord][ID: [truncatedID]24098][30k away]
12:53:23 [Combat] Activating weapon [3] on [Centus Savage Lord][ID: [truncatedID]24098][30k away]
12:53:25 [Combat] Activating weapon [1] on [Centus Savage Lord][ID: [truncatedID]24098][31k away]
12:53:25 [Combat] Activating weapon [4] on [Centus Savage Lord][ID: [truncatedID]24098][31k away]
12:53:34 [Panic] Adding [Sansha's Berserker][ID: [truncatedID]24087] as a PrimaryWeaponPriorityTarget
12:53:49 [Defense] Shields: [99%] Cap: [58%] Shield Booster: [1] deactivated [2] sec reactivation delay
12:53:49 [Combat] Targeting priority target [Sansha's Berserker][ID: [truncatedID]24087][6k away] highValueTargets.Count [4]
12:53:53 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 573 MB
12:53:53 [Cleanup.CleanupTasks] EVEMemoryManager: running [dotnet memmanager memmanager 524288000 ](500MB ceiling)
12:53:54 [Combat] Activating weapon [2] on [Sansha Slaver][ID: [truncatedID]24071][17k away]
12:53:54 [Combat] Activating weapon [3] on [Sansha Slaver][ID: [truncatedID]24071][17k away]
12:53:56 [Combat] Activating weapon [1] on [Sansha Slaver][ID: [truncatedID]24071][17k away]
12:53:56 [Combat] Activating weapon [4] on [Sansha Slaver][ID: [truncatedID]24071][17k away]
12:53:58 [Salvage] Opening container [Centatis Specter Wreck][1k][ID: [truncatedID]34564]
12:54:02 [Salvage] Cargo Container [Centatis Specter Wreck][1k][ID: [truncatedID]34564] within loot range, unlocking container.
12:54:03 [Salvage] Opening container [Centatis Specter Wreck][1k][ID: [truncatedID]34564]
12:54:03 [Salvage.LootWrecks] Container [Centatis Specter Wreck][1k][ID: [truncatedID]34564] contained no valuable items
12:54:24 [Combat] Targeting high value target [Sansha Slaver][ID: [truncatedID]24075][33k away] highValueTargets.Count [4]
12:54:25 [Combat] Activating weapon [1] on [Sansha's Berserker][ID: [truncatedID]24087][6k away]
12:54:26 [Salvage] Locking [Centum Loyal Fiend Wreck][15k][ID: [truncatedID]36702][15k away]
12:54:27 [Combat] Activating weapon [3] on [Sansha's Berserker][ID: [truncatedID]24087][6k away]
12:54:27 [Combat] Activating weapon [4] on [Sansha's Berserker][ID: [truncatedID]24087][6k away]
12:54:32 [Combat] Activating weapon [2] on [Sansha's Berserker][ID: [truncatedID]24087][6k away]
12:54:32 [Salvage] Activating tractorbeam [1] on [Centum Loyal Fiend Wreck][15k][ID: [truncatedID]36702]
12:54:41 [Combat] Targeting high value target [Sansha Heavy Missile Battery][ID: [truncatedID]24054][24k away] highValueTargets.Count [4]
12:54:41 [Drones] [Sansha Slaver][ID: [truncatedID]24075][32k away] is now the target for drones
12:54:42 [Drones] Engaging [ 5 ] drones on [Sansha Slaver][ID: [truncatedID]24075]32k away]
12:54:47 [Defense] Shields: [65%] Cap: [58%] Shield Booster: [1] activated
12:54:57 [Salvage] Cargo Container [Centum Loyal Fiend Wreck][1k][ID: [truncatedID]36702] within loot range, unlocking container.
12:54:58 [Salvage] Opening container [Centum Loyal Fiend Wreck][1k][ID: [truncatedID]36702]
12:55:03 [Salvage] Opening container [Centum Loyal Fiend Wreck][1k][ID: [truncatedID]36702]
12:55:03 [Salvage.LootWrecks] Container [Centum Loyal Fiend Wreck][1k][ID: [truncatedID]36702] contained no valuable items
12:55:08 [Defense] Shields: [97%] Cap: [50%] Shield Booster: [1] deactivated [2] sec reactivation delay

**Comment by Smellyarmpits** [comment]
do you need more/different log excerpt?

**Comment by Smellyarmpits** [comment]
is no one else experiencing this issue?>

**Comment by Smellyarmpits** [comment]
Still a problem

**Comment by drokk99** [comment]
yes, I have seen this, drones attacking bs while i am shooting frigs. hasn't bothered me too much though, as I can still get the frigs no probs, but it is annoying wasting ammo on frigs. Does not seem to be constant though.

**Comment by Smellyarmpits** [comment]
Fixed the problem by reverting to earlier code downloaded 12/17/12.

**Comment by oldmeat** [comment]
For me the same. I use release from January 22 and work properly.

**Comment by kn0xv1lle** [comment]
Got the issue when fighting drones.  I

 [Drones] Engaging [ 5 ] drones on [Sunder Alvi][ID: [truncatedID]34927]2k away]
 [Combat] Targeting priority target [Strain Infester Alvi][ID: [truncatedID]34925][2k away] highValueTargets.Count [3]
 [Panic] Adding [Sunder Alvi][ID: [truncatedID]34927] as a PrimaryWeaponPriorityTarget
 [CombatMissionCtrl.ClearPocket] Aligning to the Star so we might possibly hit [Sunder Alvi][ID: [truncatedID]34927][ActiveShip.Entity.Mode:[0]
 [CombatMissionCtrl.ClearPocket] Initiating Orbit [Sunder Alvi][at 25k][ID: [truncatedID]34927]
 [Combat] Activating weapon  [1] on [Sunder Alvi][ID: [truncatedID]34927][2k away]
 [Combat] Activating weapon  [1] on [Raider Alvi][ID: [truncatedID]34924][8k away]
 [Drones] [Raider Alvi][ID: [truncatedID]34924][8k away] is now the target for drones
 [Combat] Targeting priority target [Sunder Alvi][ID: [truncatedID]34927][2k away] highValueTargets.Count [2]
 [Drones] Engaging [ 5 ] drones on [Raider Alvi][ID: [truncatedID]34924]8k away]
 [Panic] Adding [Raider Alvi][ID: [truncatedID]34924] as a PrimaryWeaponPriorityTarget

The line where it says panic makes him shoot the drone and drones get on another target. Most bs which breaks the whole fighting.

**Comment by ISeeDEDPpl** [comment]
this should be fixed in bleedingedge atm. please test and report back. I will need logs if it is not working as you think it should. keep in mind that ALL ewar is checked in panic (background process) and it decides based on what is fitted to your ship if it should make it a priority target or not:

Warp Scramblers: always a DronePriorityTarget, only a PrimaryWeaponPriorityTarget if ShootWarpScramblersWithPrimaryWeapons is true
Webbers: a PrimaryWeaponPriorityTarget (and DronePriorityTarget) IF you have speedtank true
Neutralizers: always a PrimaryWeaponPriorityTarget (and DronePriorityTarget if it is a frigate)
ECM: always a PrimaryWeaponPriorityTarget (and DronePriorityTarget if it is a frigate)
SensorDamps: always a PrimaryWeaponPriorityTarget (and DronePriorityTarget if it is a frigate)
TrackingDisruption: if you are using turrets (not missiles) it will be a PrimaryWeaponsPrioritytarget (and  dronePriorityTarget if it is a frigate)

Any suggestions on changing the above logic are welcome.

**Comment by kn0xv1lle** [comment]
Well i have a suggestion. I always watched my gunboat which is also speed tanking ignoring frigs as set in   <speedNPCFrigatesShouldBeIgnoredByPrimaryWeapons>100</speedNPCFrigatesShouldBeIgnoredByPrimaryWeapons>
  <distanceNPCFrigatesShouldBeIgnoredByPrimaryWeapons>15000</distanceNPCFrigatesShouldBeIgnoredByPrimaryWeapons>

but if the frig is a webber he switches his primary weapons on this frig although he should ignore it like it is set because he can t hit it with his guns. So he ignores the settings because of the speed tanking setting when the frig is a webber. This is not very effective because it makes no difference if he can t hit it. Could you change this that the setting is considered?

**Comment by Smellyarmpits** [comment]
Logic answers below:

Warp Scramblers: always a DronePriorityTarget, only a PrimaryWeaponPriorityTarget if ShootWarpScramblersWithPrimaryWeapons is true.  

This is okay since one can force guns not to attack scrammers.  BS guns can't hit anything in the range that a scrammer would orbit.  Drone primary ALWAYS

Webbers: a PrimaryWeaponPriorityTarget (and DronePriorityTarget) IF you have speedtank true

This shouldn't be the case.  Webbers like scrammers will orbit at ranges that BS guns can't hit.  This should be selectable like scrammers.  Drone primary ALWAYS

Neutralizers: always a PrimaryWeaponPriorityTarget (and DronePriorityTarget if it is a frigate)

This should be true ONLY IF the neuter is 10-15kms from ship AND should always be primary for drones.

ECM: always a PrimaryWeaponPriorityTarget (and DronePriorityTarget if it is a frigate)

This should be true ONLY IF the neuter is 10-15kms from ship AND should always be primary for drones.  Drone primary ALWAYS

SensorDamps: always a PrimaryWeaponPriorityTarget (and DronePriorityTarget if it is a frigate)

This should be true ONLY IF the neuter is 10-15kms from ship AND should always be primary for drones.  Drone primary ALWAYS

TrackingDisruption: if you are using turrets (not missiles) it will be a PrimaryWeaponsPrioritytarget (and dronePriorityTarget if it is a frigate)

This should be true ONLY IF the neuter is 10-15kms from ship AND should always be primary for drones.  Drone primary ALWAYS

Logic should also be to attack with primary guns any frigs at 20kms or more.  Anything below that should be a drone primary.  Once all drones 20kms or more are eliminated, move to crusiers then BS's.  Once all targets 20kms (maybe selectable in the config.xml) or more have been eliminated use primary guns on anything left.

Too many times do I find my guns missing away at targets >10 when there are 50 targets in or just outside of optimal range.  My cap and ammo get eaten up because I am missing and npc's that I could 1-5 shot keep pounding away on my ship.  Hope that helps in the logic department.

I will be testing bleeding today with the newest DE.

**Comment by Smellyarmpits** [comment]
I hate to pile on, but would it be possible to:

1)  Drone delay - when drones are attacked they dock, but seem to still be a target after they come back out (sometimes).  Would it be possible to have them wait in the drone bay for 1 maybe 2 more seconds to ensure agro is lost?

2) Selective drone recall.  When drones are attacked all drones return.  would it be possible for only the drone being attacked to return?

**Comment by kn0xv1lle** [comment]
Well the  <speedNPCFrigatesShouldBeIgnoredByPrimaryWeapons>100</speedNPCFrigatesShouldBeIgnoredByPrimaryWeapons>
  <distanceNPCFrigatesShouldBeIgnoredByPrimaryWeapons>15000</distanceNPCFrigatesShouldBeIgnoredByPrimaryWeapons>

is the right setting to avoid that. Although its not working correct. Somehow targets which were marked as ignored by primary weapons still get to the primary weapon list. This is happening when the target is a webber and speed tank is active. First he ignores it but then when webbers goes active after some time he starts fireing. 
I think this:"Webbers: a PrimaryWeaponPriorityTarget (and DronePriorityTarget) IF you have speedtank true"
 is the key of the problem. Needs to be fixed because guns will never hit a frigate orbiting you inside your dead angle. Setting above should avoid this behaviour if its working correct.

**Comment by Smellyarmpits** [comment]
ISDP I tested bleeding.  The behavior seems to be fixed as it relates to the first issue - primary guns stuck on frig while drones attack a BS far off, but the logic and "pile on" request are still valid.  

Also, the targeting issue that others have described is still true - i.e. NPC's that have been targeted are not able to be shot by the primary weapons - message given in game interface is "XXXX deactivated because xxxx is not a valid target" or something similar. 

Reverting to 2/23/13 build to bot

**Comment by ISeeDEDPpl** [comment]
I'll look at adding the additional logic over the next few days. for now the biggest prob has been fixed here. Ill keep this open until the other things discussed have been addressed.

**Comment by ISeeDEDPpl** [comment]
ok, I think everything has been addressed in bleedingedge. If you see any other issues or have suggestions open a new issue.
