### ISSUE TITLE
errors in QuestorManager

### ISSUE THREAD

**Issue by KingMike** [ISeeDEDPpl/Questor#505]
QuestorManager show errors in logs:

[Cache.SolarSystems] Exception [System.NullReferenceException: Object reference not set to an instance of an object.
 at DirectEve.DirectSolarSystem.(DirectEve )
 at DirectEve.DirectEve.get_SolarSystems()
 at Questor.Modules.Caching.Cache.get_SolarSystems() in C:\Questor-BleedingEdge\Questor.Modules\Caching\Cache.cs:line 2047]

I am not sure if it will work with those errors anyway as I stopped it after seeing the errors.

Using BE f57bc3a592af604e41f847b87fe3a1b912467a6a

Thanks!

**Comment by ISeeDEDPpl** [comment]
this _might_ be fixed in latest BE. please test again.

**Comment by KingMike** [comment]
Hello,

Thanks for looking into it.
It now shows different error (different line).

[Cache.SolarSystems] Exception [System.NullReferenceException: Object reference not set to an instance of an object.
 at DirectEve.DirectSolarSystem.(DirectEve )
 at DirectEve.DirectEve.get_SolarSystems()
 at Questor.Modules.Caching.Cache.get_SolarSystems() in C:)\Questor-BleedingEdge\Questor.Modules\Caching\Cache.cs:line 2049]

commit: 20a82f80cfc5901f0c09d3b4919088550f5df113

Thanks!

**Comment by ISeeDEDPpl** [comment]
2nd pass...

**Comment by KingMike** [comment]
same errors still. sorry. even with d3e512f420bee719c9128c27c93a7363451ad609

QM works (well the traveller is). Those errors only happen after launching QM.
About 5-6 times. the same error.
Then it all looks OK.

**Comment by ISeeDEDPpl** [comment]
odd, its like DE does not return the list correctly on the 1st pass and take a few seconds to build the list of systems and then it works =/

**Comment by ISeeDEDPpl** [comment]
fixed by ignoring the nulref. it only happens when we first call DE to list the solarsystems as DE is gathering the data from eve (seemingly)
